"""Public package boundary for agent-session-harness."""

from .guardian_bake import (
    GuardianBakeDecision,
    GuardianBakeError,
    GuardianBakeReport,
    GuardianHighWaterMarks,
    ObservationWindow,
    ResourceHighWaterMarks,
    UsageHighWaterMarks,
)
from .guardian_bake_runtime import (
    GuardianBakeConfig,
    GuardianBakeExitAssessment,
    GuardianBakeMode,
    assess_bake_exit,
)
from .process_identity import (
    ManagedResourceReference,
    ProcessEvidence,
    ProcessIdentity,
    ProcessInspector,
    ProcessObservation,
    ProcessPlatform,
    ProcessState,
    capture_process_identity,
    same_process,
)
from .resource_guardian import (
    GuardianAction,
    GuardianDecision,
    GuardianEvidence,
    GuardianObservation,
    GuardianReasonCode,
    LeaseState,
    ManagedOwnerState,
    ManagedResource,
    OwnerLeaseIdentity,
    ProcessIdentityState,
    WorktreeIdentity,
    WorktreeState,
    decide_guardian_action,
)

__version__ = "0.1.0"

__all__ = [
    "GuardianAction",
    "GuardianBakeConfig",
    "GuardianBakeDecision",
    "GuardianBakeError",
    "GuardianBakeExitAssessment",
    "GuardianBakeMode",
    "GuardianBakeReport",
    "GuardianDecision",
    "GuardianEvidence",
    "GuardianHighWaterMarks",
    "GuardianObservation",
    "GuardianReasonCode",
    "LeaseState",
    "ManagedOwnerState",
    "ManagedResource",
    "ManagedResourceReference",
    "ObservationWindow",
    "OwnerLeaseIdentity",
    "ProcessEvidence",
    "ProcessIdentity",
    "ProcessIdentityState",
    "ProcessInspector",
    "ProcessObservation",
    "ProcessPlatform",
    "ProcessState",
    "ResourceHighWaterMarks",
    "UsageHighWaterMarks",
    "WorktreeIdentity",
    "WorktreeState",
    "__version__",
    "assess_bake_exit",
    "capture_process_identity",
    "decide_guardian_action",
    "same_process",
]
